apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
  name: api-service
spec:
  ports:
  - name: http
    port: 8080
    nodePort: 31608
    targetPort: 8080
  selector:
    app: api-pod
  type: NodePort